### NumPy First Steps

### Programming for Data Science
### Last Updated: Jan 15, 2023
---  

### PREREQUISITES
- import
- functions
- for ... in

### SOURCES 
- **Python for Data Analysis, Chapter 4 (be sure to read this)**
- https://numpy.org/
- https://en.wikipedia.org/wiki/NumPy
- https://www.scipy.org/
- https://en.wikipedia.org/wiki/SciPy
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
- https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

### OBJECTIVES
- Take your first steps with numpy
 


### CONCEPTS

- The numpy package contains useful functions for math operations
- The ndarray is the workhorse of the package


---

### numpy

In this lesson we will explore the python package *numpy*.  
This package is super powerful. 

Our focus will be on:
- importing and calling some random number generating functions
- illustrating operations on ndarrays
- learning how to subset ndarrays

### Motivation

I need a random number! I heard numpy can do that!  

In [1]:
import numpy as np
np.random.randint(1,7)

3

Learn what this function does:

In [2]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer t

Include the size parameter to generate 10 random integers in [1, 6]

In [3]:
np.random.randint(1,7,10)

array([2, 6, 4, 3, 4, 3, 6, 2, 5, 6])

---

### The ndarray in Numpy

Details [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

Represents a multidimensional, homogeneous array of fixed-size items. 

Uses very efficient operations

Arrays should be constructed using `array()`, `zeros()` or `empty()`.

### NumPy ndarray Operations


Create an array with some data

In [4]:
x = np.array(([2,3,1],[3,1,2]))
print(x)
x

[[2 3 1]
 [3 1 2]]


array([[2, 3, 1],
       [3, 1, 2]])

Get the shape of the data (rows, columns)

In [7]:
print(x.shape)

(2, 3)


In [8]:
# generate matrix of random normals 

x = np.random.randn(2, 3)
x

array([[ 0.32827462,  1.94056163,  0.91556003],
       [ 1.63798003, -0.71371497,  1.15507124]])

In [9]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribu

Scale the matrix - notice how this operates elementwise

In [10]:
x * 2

array([[ 0.65654923,  3.88112325,  1.83112007],
       [ 3.27596005, -1.42742994,  2.31014249]])

Addition

In [11]:
x + x

array([[ 0.65654923,  3.88112325,  1.83112007],
       [ 3.27596005, -1.42742994,  2.31014249]])

Reciprocal

In [12]:
1 / x

array([[ 3.04623006,  0.51531474,  1.09222767],
       [ 0.61050805, -1.40111956,  0.86574746]])

#### Creating Matrices with Special Structure - can create arrays of zeros, ones, and identity matrices

In [7]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [8]:
x.shape

(5,)

In [15]:
y=np.zeros([5,1])

In [16]:
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [17]:
y.shape

(5, 1)

In [18]:
z=np.zeros([1,5])
print(z)

[[0. 0. 0. 0. 0.]]


In [19]:
z.shape

(1, 5)

In [20]:
q=np.zeros((2,3))
print(q)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
q.shape

(2, 3)

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Indexing and Slicing

In [ ]:
z = np.random.randint(5)
z

array([-0.4840453 , -0.51934137, -0.35498288,  0.14279941, -0.46709961])

In [25]:
# select from start to one before end
z[1:4]

array([-0.51934137, -0.35498288,  0.14279941])

In [26]:
# does this make sense?
z[1:-1]

array([-0.51934137, -0.35498288,  0.14279941])

In [31]:
# boolean indexing
z[z>0.15]

array([3.])

In [28]:
# assignment
z[1] = 3
z

array([-0.4840453 ,  3.        , -0.35498288,  0.14279941, -0.46709961])

In [29]:
# 2D
w = np.random.randn(3,3)
w

array([[ 0.90643094,  0.24626165, -1.79390875],
       [ 0.03763664,  0.71116469,  1.19864638],
       [-0.73119515, -1.52330416,  2.04254054]])

In [33]:
# subset rows and columns
w[1:, :2]

array([[ 0.03763664,  0.71116469],
       [-0.73119515, -1.52330416]])

#### TRY FOR YOURSELF
Write code to generate a new array *w2* that starts with *w* and sets all negative values to 0.
Then print *w2* and *w*.  

Be sure to use:  
w2 = w.copy()  
or w will get updated as well

In [32]:
w2 = w.copy()
w2[w2 < 0] = 0
print('w2:\n', w2)
print('')
print('w:\n', w)

w2:
 [[0.90643094 0.24626165 0.        ]
 [0.03763664 0.71116469 1.19864638]
 [0.         0.         2.04254054]]

w:
 [[ 0.90643094  0.24626165 -1.79390875]
 [ 0.03763664  0.71116469  1.19864638]
 [-0.73119515 -1.52330416  2.04254054]]


In [ ]:
w2 = w.copy()
w2[w2 < 0] = 0
print('w2:\n', w2)
print('')
print('w:\n', w)

---  

#### Next Steps

This notebook provided some information to get you started.

To learn more, please refer to your textbook and the links in the Sources section at top.